<?php

return [
    'logo' => [
        'title_main' => "Logo",
        'kind' => 'static',
        'title' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 134,
        'height' => 46,
        'opt' => 1,
        'thumb' => '134x46x1',
    ],
    'favicon' => [
        'title_main' => "Favicon",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 48,
        'height' => 48,
        'thumb' => '48x48x1',
    ],
    'slide' => [
        'title_main' => "Slideshow",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 1920,
        'height' => 775,
        'opt' => '1',
        'thumb' => '1920x775x2',
    ],
    'tieu-chi' => [
        'title_main' => "Tiêu chí",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => false,
        'name' => true,
        'desc' => true,
        'desc_cke' => false,
        'width' => 40,
        'height' => 40,
        'opt' => '1',
        'thumb' => '40x40x1',
    ],
    'doi-tac' => [
        'title_main' => "Đối tác",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 200,
        'height' => 160,
        'opt' => '1',
        'thumb' => '200x160x1',
    ],
    'social' => [
        'title_main' => "Social left",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 37,
        'height' => 37,
        'opt' => '1',
        'thumb' => '37x37x2',
    ],
    'mangxahoi' => [
        'title_main' => "Social Footer",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 4,
        'show_images' => true,
        'images' => true,
        'avatar' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'width' => 37,
        'height' => 37,
        'opt' => '1',
        'thumb' => '37x37x2',
    ],
    'watermark_product' => [
        'title_main' => "Đóng dấu",
        'kind' => 'static',
        'watermark' => true,
        'desc' => false,
        'title' => false,
        'desc_cke' => false,
        'link' => false,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 200,
        'height' => 200,
        'thumb' => '200x200x1',
    ],
    'banner_menu' => [
        'title_main' => "Banner menu",
        'kind' => 'static',
        'title' => true,
        'status' => ["hienthi" => "Hiển thị"],
        'images' => true,
        'width' => 210,
        'height' => 323,
        'opt' => 1,
        'thumb' => '210x323x1',
    ],
    'banner_quangcao' => [
        'title_main' => "Banner quảng cáo",
        'kind' => 'album',
        'status' => ["hienthi" => "Hiển thị"],
        'number' => 5,
        'images' => true,
        'show_images' => true,
        'gallery' => true,
        'link' => true,
        'name' => true,
        'desc' => false,
        'desc_cke' => false,
        'width' => 1770,
        'height' => 560,
        'opt' => '1',
        'thumb' => '1770x560x1',
    ],
    'video' => [
        'title_main' => "Video",
        'kind' => 'static',
        'status' => ["hienthi" => "Hiển thị"],
        'link' => true,
        'name' => true,
    ],
];
